spring:
  #  mvc:
  #    static-path-pattern: /res/** # 配置之后导致welcome page 功能失效
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  resources:
    static-locations: [ classpath:/haha/ ]
    add-mappings: true
    cache:
      period: 11000
